// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/ww24/graphql-tutorial/domain/service"
	"github.com/ww24/graphql-tutorial/infra/db"
	"github.com/ww24/graphql-tutorial/presentation/graphql/resolver"
)

// Injectors from wire.go:

func register() *server {
	schedule := db.NewSchedule()
	user := db.NewUser()
	scheduleImpl := service.NewSchedule(schedule, user)
	userImpl := service.NewUser(user)
	resolverResolver := resolver.NewResolver(scheduleImpl, userImpl)
	mainServer := newServer(resolverResolver, userImpl, scheduleImpl)
	return mainServer
}
