// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewSchedule struct {
	Title               string    `json:"title"`
	StartAt             time.Time `json:"startAt"`
	EndAt               time.Time `json:"endAt"`
	UserID              string    `json:"userId"`
	Description         *string   `json:"description"`
	ParticipantsUserIds []string  `json:"participantsUserIds"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Schedule struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	StartAt      time.Time `json:"startAt"`
	EndAt        time.Time `json:"endAt"`
	CreatedBy    *User     `json:"createdBy"`
	Description  *string   `json:"description"`
	Participants []*User   `json:"participants"`
}

type User struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Schedules []*Schedule `json:"schedules"`
}
